name: Build and Publish (main)

on:
  push:
    branches: [ main ]

concurrency:
  group: publish-main
  cancel-in-progress: false

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          scope: '@cyberwareai'
          always-auth: true

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies (bun)
        run: bun install --frozen-lockfile || bun install

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Increment version
        run: |
          # Get current version for logging
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "Current version: $CURRENT_VERSION"
          
          # Increment patch version
          npm version patch --no-git-tag-version
          
          # Get new version for logging
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "New version: $NEW_VERSION"

      - name: Commit and push version bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add package.json
          NEW_VERSION=$(node -p "require('./package.json').version")
          git commit -m "chore: bump version to $NEW_VERSION [skip ci]"
          git push

      - name: Build package
        run: bun run build || npm run build

      - name: Configure npm auth
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          echo "@cyberwareai:registry=https://registry.npmjs.org" >> ~/.npmrc

      - name: npm diagnostics
        run: |
          echo "whoami: $(npm whoami 2>/dev/null || echo '<not authed>')"
          echo "list org packages (may be empty on first publish):"
          npm access list packages @cyberwareai || true
          PKG_NAME=$(node -p "require('./package.json').name")
          PKG_VERSION=$(node -p "require('./package.json').version")
          echo "Publishing: $PKG_NAME@$PKG_VERSION"

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --access public --ignore-scripts


